### ISSUE TITLE
Why use a fakeContext?

### ISSUE THREAD

**Issue by Vadorequest** [geovanisouza92/serverless-next#5]
At https://github.com/geovanisouza92/serverless-next/blob/master/aws/web.js you use a `fakeContext`. Why not just pass the `context` instead? What issue does it solve?

**Comment by geovanisouza92** [comment]
Hi @vadorequest,

Context has been [deprecated for newer versions of node.js](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html) by AWS itself. The only thing used is the succeed method, and the polymorphic callback is the way to go since then.

**Comment by Vadorequest** [comment]
I don't see such thing in the link you provided. I see `context` is unusable with node 0.10, but perfectly viable with 6.10. Also, nothing is said such as being deprecated in the doc https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

**Comment by geovanisouza92** [comment]
https://github.com/awslabs/aws-serverless-express/issues/32

aws-serverless-express still didn't changed it's signature, so the `fakeContext`.

---

P.S.: Beyond that, callback is much more aligned with Node.js ecosystem overall, [it have been rediscovered as a powerful primitive](https://github.com/staltz/callbag-basics).

---

P.S. 2: Please, feel free to use which method you find more suitable.

---

P.S. 3: I'm working on a new version of this reference implementation at https://github.com/geovanisouza92/serverless-next5 and I'll include some rationale of my choices over there. :)

**Comment by Vadorequest** [comment]
Okay! Thanks for the feedback, meantime I've added a lot of doc on my own repo. ;)
